# 这是一个示例 mods.toml 文件，其中包含与加载模组相关的数据。
# 文件中有若干必填字段（#必填项），以及更多可选字段（#可选）。
# 整体格式采用标准 TOML 格式，版本为 v0.5.0。
# 请注意，此文件中包含几个 TOML 列表。
# 有关 toml 格式的更多信息，请访问：https://github.com/toml-lang/toml
# 指定要加载的模组加载器类型名称——对于常规 FML @Mod 模组，应设为 javafml
modLoader = "javafml" #必填项
# 该模组加载器对应的版本范围——对于常规的FML @Mod而言，此范围将指代Forge版本。
loaderVersion = "${loader_version_range}" #必填项 这通常由Forge在每个Minecraft版本更新时进行版本号提升。具体版本列表请参见我们的下载页面。
# 您模组的许可证。这是必需的元数据，有助于更清晰地了解您的再分发权限。
# 请访问 https://choosealicense.com/ 查看您的选项。默认情况下采用“保留所有权利”的版权立场，因此此处也默认如此。
license = "MIT"
# 当此模组出现问题时，用于向用户反馈的网址链接
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #可选
# 模组列表 - 此处允许的模组数量由各模组加载器自行决定
[[mods]] #必填项
# 模组的标识符
modId = "kachu" #必填项
# 模组版本号
version = "${mod_version}" #必填项
# 模组的显示名称
displayName = "Kachu's Delight" #必填项
# 用于查询此模组更新的URL。请参阅JSON更新规范：https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #可选
# 此模组的“主页”URL，将在模组界面中显示
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #可选
# 包含显示徽标的文件名（位于模组JAR文件根目录）
#logoFile="dumplingsdelight.png" #可选
# 在模组界面中显示的文本字段
#credits="此示例模组感谢Java提供支持" #可选
# 在模组界面中显示的文本字段
authors = "香奶美天下第一，弦化卷着导" #可选
# 显示测试控制你的模组在服务器连接界面中的显示方式
# MATCH_VERSION 表示当客户端与服务器版本不一致时，你的模组会显示红叉。这是默认行为，如果你的模组同时包含服务器和客户端组件，应选择此项。
# IGNORE_SERVER_VERSION 表示当模组存在于服务器但不存在于客户端时，不会触发红叉。纯服务器模组应使用此选项。
# IGNORE_ALL_VERSION 表示无论模组存在于客户端还是服务器，都不会触发红叉。此为特殊情况，仅适用于无服务器组件的模组。
# NONE 表示未为你的模组设置显示测试。你需要自行处理，详见 IExtensionPoint.DisplayTest 的说明。使用此值时可以自定义任何方案。
# 重要提示：这并非指示你的模组在哪些环境（客户端或专用服务器）加载。无论处于何种环境，你的模组都应正常加载（即使可能不执行任何操作！）。
# displayTest="MATCH_VERSION" # 若未指定任何值，默认使用 MATCH_VERSION（#可选）

# 模组描述文本（多行！）（#必填项）
description = '''${mod_description}'''
# 依赖项 - 使用点号表示特定模组ID的依赖关系。依赖项是可选的。
[[dependencies.${mod_id}]] #可选
# 依赖项的模组ID
modId = "forge" #必填项
# 此依赖关系是否必须存在 - 若非必需，则必须指定以下顺序
mandatory = true #必填项
# 依赖项的版本范围
versionRange = "${forge_version_range}" #必填项
# 依赖项的排序关系 - 如果依赖项非必需，则需指定为BEFORE或AFTER
# BEFORE - 此模组在依赖项之前加载
# AFTER - 此模组在依赖项之后加载
ordering = "NONE"
# 该依赖项所应用的一侧 - BOTH（两端）、CLIENT（客户端）或 SERVER（服务器端）
side = "BOTH"# 这是另一个依赖项
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
# 此版本范围声明了从当前Minecraft版本的最低要求开始，直至但不包括下一个主要版本
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="farmersdelight"
mandatory=true
versionRange="[1.2.0,)"
ordering="BEFORE"
side="BOTH"